USE [master]
GO

/****** Object:  Database [testing]    Script Date: 9/2/2020 3:33:26 PM ******/
CREATE DATABASE [testing]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'testing', FILENAME = N'C:\Users\Canterini\testing.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'testing_log', FILENAME = N'C:\Users\Canterini\testing_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [testing].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [testing] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [testing] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [testing] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [testing] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [testing] SET ARITHABORT OFF 
GO

ALTER DATABASE [testing] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [testing] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [testing] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [testing] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [testing] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [testing] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [testing] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [testing] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [testing] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [testing] SET  DISABLE_BROKER 
GO

ALTER DATABASE [testing] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [testing] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [testing] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [testing] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [testing] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [testing] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [testing] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [testing] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [testing] SET  MULTI_USER 
GO

ALTER DATABASE [testing] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [testing] SET DB_CHAINING OFF 
GO

ALTER DATABASE [testing] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [testing] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [testing] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [testing] SET QUERY_STORE = OFF
GO

USE [testing]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [testing] SET  READ_WRITE 
GO

