//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pruebaInnerCB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public int idArticulo { get; set; }
        public int IdBodega { get; set; }
        public string Descripcion { get; set; }
        public int Precio { get; set; }
        public int Stock { get; set; }
    
        public virtual Bodega Bodega { get; set; }
    }
}
